#!/bin/bash

# configuration
export IS_MA__UPS_PATH=/home/deploy/.is-ma/ups
export IS_MA__WEBLOG_PATH=/var/log/nginx/ups_access.log
export IS_MA__MAX_REQ_MIN=30
export IS_MA__PUBLIC_TXT_FOR_TASKER=/home/deploy/rank_app/code/public/lastminuteplus.txt

# offender xploit filters
starting_with=" /\.git/"\
"| /\.aws/"\
"| /__phpmyadmin"\
"| /_ignition"\
"| /_phpmyadmin"\
"| /2phpmyadmin/"\
"| /actuator/"\
"| /administrator/"\
"| /admin/"\
"| /api/"\
"| /autodiscover/"\
"| /aws/"\
"| /boaform/"\
"| /core/"\
"| /credentials"\
"| /data/"\
"| /dbadmin/"\
"| /db/"\
"| /debug/"\
"| /geoserver/"\
"| /laravel/"\
"| /manager/"\
"| /myadmin/"\
"| /mysql"\
"| /phpmy\-admin/"\
"| /phpmyadmin"\
"| /phppma/"\
"| /phpunit/"\
"| /pma/"\
"| /pools/"\
"| /private/"\
"| /program/"\
"| /shopdb/"\
"| /sites/"\
"| /sql/"\
"| /sqlmanager/"\
"| /system/"\
"| /test/"\
"| /uploads/"\
"| /vendor/"\
"| /wordpress/"\
"| /wp/"\
"| /wp\-admin/"\
"| /wp\-content/"\
"| /wp\-includes/"

ending_in="\.7z "\
"|\.asp "\
"|\.aspx "\
"|\.bak "\
"|\.backup "\
"|\.bk "\
"|\.bz2 "\
"|\.cgi "\
"|\.dll "\
"|\.env "\
"|\.envrc "\
"|\.ini "\
"|\.jhtml "\
"|\.jar "\
"|\.jsa "\
"|\.php "\
"|\.pl "\
"|\.swp "\
"|\.sql "\
"|\.tar "\
"|\.war "\
"|\.zip "\
"|/setup\.txt "

export IS_MA__XPLOIT_DIC="$starting_with|$ending_in"
